name: "release-please-dotnet"
description: "Composite action to automate .NET package versioning using release-please"
inputs:
  manifest:
    description: "Path to the manifest file"
    required: false
    default: ".release-please-manifest.json"
runs:
  using: "composite"
  steps:
    - name: Install pre-requisites
      shell: bash
      run: |
        path=${GITHUB_ACTION_PATH}/prerequisites.sh
        chmod +x $path
        bash $path

    - name: Test
      shell: bash
      run: |
        if [ -f "${{ inputs.manifest }}" ]; then
          cat ${{ inputs.manifest }}
        else
          echo "File not found"
        fi
