name: "release-please-dotnet"
description: "Composite action to automate .NET package versioning using release-please"
inputs:
  manifest:
    description: "Path to the manifest file"
    required: false
    default: ".release-please-manifest.json"
  config:
    description: "Path to the release-please configuration file"
    required: false
    default: "release-please-config.json"
runs:
  using: "composite"
  steps:
    - name: Install pre-requisites
      shell: bash
      run: |
        path=${GITHUB_ACTION_PATH}/prerequisites.sh
        chmod +x $path
        bash $path

    - name: Bump versions
      shell: bash
      run: |
        path=${GITHUB_ACTION_PATH}/bump.sh
        chmod +x $path
        bash $path ${{ inputs.manifest }} ${{ inputs.config }}
