name: "release-please-dotnet"
author: "Tobias Lekman"
description: "Composite action to automate .NET package versioning using release-please"
branding:
  icon: arrow-right-circle
  color: black
inputs:
  manifest:
    description: "Path to the manifest file"
    required: false
    default: ".release-please-manifest.json"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install pre-requisites
      shell: bash
      run: |
        path=${GITHUB_ACTION_PATH}/prerequisites.sh
        chmod +x $path
        bash $path

    - name: Detect branch name
      shell: bash
      id: detect_branch
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Bump versions
      shell: bash
      run: |
        path=${GITHUB_ACTION_PATH}/bump.sh
        chmod +x $path
        bash $path ${{ inputs.manifest }} ${{ env.BRANCH_NAME }}
