name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - "main"

jobs:
  verify-prerequisites:
    name: Verify prerequisites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions
        run: chmod +x prerequisites.sh

      - name: Run prerequisites script
        run: ./prerequisites.sh

      - name: Verify outcome
        run: |
          if ! command -v gpr &> /dev/null; then
            echo "gpr tool is not installed"
            exit 1
          fi
          if ! command -v xmlstarlet &> /dev/null; then
            echo "xmlstarlet is not installed"
            exit 1
          fi
          if ! command -v xmllint &> /dev/null; then
            echo "xmllint is not installed"
            exit 1

  find:
    name: Find .csproj files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find project files
        id: find-projects
        run: |
          csproj_files=$(find . -name '*.csproj' -type f | jq -R -s 'split("\n") | map(select(length > 0))')
          echo "projects=$csproj_files" >> $GITHUB_OUTPUT

      - name: Create matrix strategy
        id: create-matrix
        run: |
          echo "matrix=${{ steps.find-projects.outputs.projects }}" >> $GITHUB_OUTPUT

  build:
    name: Build projects
    needs: find
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csproj: ${{ fromJson(needs.find.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build project
        run: dotnet build ${{ matrix.csproj }}
